version: '3'
services:
  voicerecorder:
    image: voicerecorder:$TAG
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: $JAR_FILE
    environment:
      CLOUD_AWS_REGION: us-west-1
      JAVA_OPTS: >
        -Dspring.profiles.active=dev -Dcloud.aws.region.static=${CLOUD_AWS_REGION}

    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - voicerecorder_network

  db:
    container_name: db
    image: postgres:13.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    networks:
      - voicerecorder_network
    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  s3:
    container_name: s3
    image: adobe/s3mock
    ports:
      - 9191:9191
      - 9090:9090
    environment:
      - initialBuckets=makah-asr
    networks:
      - voicerecorder_network




networks:
  voicerecorder_network:
    driver: bridge